on:
  pull_request:
  push:
    branches:
      - main

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release Please
    if: github.event_name != 'pull_request'
    steps:
#      - uses: ebcont/ebcont.it-support.action.request-app-token@v1
#        id: github_app_token
#        with:
#          github_app_id: ${{ vars.RELEASE_PLEASE_APP_ID }}
#          github_app_organization: ${{ github.repository_owner }}
#          github_app_private_key: ${{ secrets.RELEASE_PLEASE_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        id: release
#        with:
#          token: ${{ steps.github_app_token.outputs.token }}

  evaluate-checks:
    runs-on: ubuntu-latest
    if: always()
    name: Evaluate checks
    needs: [ release-please ]
    steps:
      - name: Check if all jobs have parsed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: release-please