on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release Please
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: maven
